/**
 * -----------------------------------------------------------------------------
 * Robots.txt Generator
 * -----------------------------------------------------------------------------
 * Serves `/robots.txt` to instruct search engine crawlers what they may index.
 * It exists alongside `sitemap.ts` to keep the public SEO surface limited to
 * the marketing landing page: crawlers are explicitly allowed on `/landing`
 * and blocked from the API, auth/org flows, and authenticated dashboard pages
 * (text-to-speech, voices, test). It also points crawlers at the sitemap
 * generated by `src/app/sitemap.ts`.
 */
import { MetadataRoute } from 'next';

/**
 * Builds the robots rules for all user agents.
 *
 * @returns A Next.js metadata robots config with allow/disallow paths and the
 *   absolute sitemap URL derived from APP_URL.
 */
export default function robots(): MetadataRoute.Robots {
  // Match the base URL logic in sitemap.ts so both files stay consistent.
  const baseUrl = process.env.APP_URL || 'http://localhost:3000';

  return {
    rules: {
      userAgent: '*',
      allow: ['/landing'],
      disallow: [
        '/api/',
        '/org-selection/',
        '/text-to-speech/',
        '/voices/',
        '/test/',
      ],
    },
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
